# Site settings
title: takuizum
tagline: データサイエンス・心理測定学・統計分析
description: >-
  データサイエンス、統計学、プログラミングの分野で研究・開発に従事。
  学術研究から実践的なソリューション開発まで幅広く取り組んでいます。

url: "https://takuizum.github.io"
baseurl: ""

# Author settings
author:
  name: takuizum
  email: your.email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman

# Plugins (Cayman theme compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
