# Site settings
title: PsyTestLab
tagline: データサイエンス・心理測定学・統計分析
description: >-
  データサイエンス、統計学、プログラミングの分野で研究・開発に従事。
  学術研究から実践的なソリューション開発まで幅広く取り組んでいます。

url: "https://takuizum.github.io"
baseurl: ""

# Cayman Blog Theme specific settings
header_page_ref: home

# Author settings
author:
  name: PsyTestLab
  email: sep10.taku.izum@gmail.com
  bio: >-
    研究者・データサイエンティスト。統計学・心理測定学・プログラミングの分野で活動。
  github: takuizum
  twitter: takuizum
  linkedin: # your_linkedin_profile

# Social links
social:
  email: sep10.taku.izum@gmail.com
  github: takuizum
  twitter: takuizum

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-paginate

# Pagination (一時的に無効化)
# paginate: 5
# paginate_path: "/blog/page:num/"

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/blog/category/:name/'
    tag: '/blog/tag/:name/'

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.config.js
  - rollup.config.js

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "PsyTestLab"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Site navigation
navigation:
  - title: "ホーム"
    url: "/"
  - title: "自己紹介"
    url: "/profile/"
  - title: "出版・論文"
    url: "/publications/"
  - title: "ブログ"
    url: "/blog/"

# Social links
social:
  github: takuizum
  twitter: # your_handle
  linkedin: # your_profile
  email: your.email@example.com

# Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Comments (optional)
# disqus:
#   shortname: your_disqus_shortname

# SEO settings
lang: ja
timezone: Asia/Tokyo
